### ISSUE TITLE
how can we redirect to route here

### ISSUE THREAD

**Issue by Alfraganus** [gmaccario/simple-mvc-php-framework#1]
I was creating an application using this MVC and I could not manage to redirect to route, can you help me with this

**Comment by gmaccario** [comment]
Hi, yes sure what is the issue? Can you explain to me a little bit more? Thanks

**Comment by gmaccario** [comment]
Hi @Alfraganus  

I merged a fix, can you check, please?

**Comment by Alfraganus** [comment]
thank you, I will check it

**Comment by gmaccario** [comment]
Hey @Alfraganus did you had any chance to get a try? I would like to close the issue

**Comment by koredalin** [comment]
Hello @gmaccario,
I have installed a clear version of your framework. But cannot open any route.
I have installed XAMPP with php7.4. I'm trying to open the routes as "localhost/folder_name/" or "localhost/folder_name/public/". What I do wrong?

Thank you
Hristo

**Comment by gmaccario** [comment]
Hi @koredalin I will check it and I'll let you know. Thanks

**Comment by koredalin** [comment]
> Hello @gmaccario,
> I have installed a clear version of your framework. But I cannot open any route.
> I have installed XAMPP with php7.4. I'm trying to open the routes as "localhost/folder_name/" or "localhost/folder_name/public/". What I do wrong?
> 
> Thank you
> Hristo

I have understood what I've made wrong.
The routes in the "routes/web.php" should be starting with "/project_folder_name/" as it is a subfolder of _htdocs_ (for example) folder. :-)
Please, add a few rows in your guide on "https://www.giuseppemaccario.com/how-to-build-a-simple-php-mvc-framework/".

**Comment by koredalin** [comment]
> > Hello @gmaccario,
> > I have installed a clear version of your framework. But I cannot open any route.
> > I have installed XAMPP with php7.4. I'm trying to open the routes as "localhost/folder_name/" or "localhost/folder_name/public/". What I do wrong?
> > Thank you
> > Hristo
> 
> I have understood what I've made wrong.
> The routes in the "routes/web.php" should be starting with "/project_folder_name/" as it is a subfolder of _htdocs_ (for example) folder. :-)
> Please, add a few rows in your guide on https://www.giuseppemaccario.com/how-to-build-a-simple-php-mvc-framework/.

define('URL_ROOT', 'http://localhost/');
I found it lastly. :-)

Thank you.
Hristo

**Comment by gmaccario** [comment]
Hi @koredalin Hi @Alfraganus 

I made some changes in order to make it compatible with a subfolder. 

Pull the changes, then add the name of your subfolder into *./config/config.php* 
as the value of this constant: _URL_SUBFOLDER_.

I updated also the guide on my blog.

Please, let me know if my changes are correct and if the application is working for you now.

Many thanks.

**Comment by koredalin** [comment]
> se, let me know if my changes are correct and if the application is working fo

Thank you, @gmaccario for the new functionality.
I'm working on other project now. But I'll check this when I can.

Regards
Hristo
