### ISSUE TITLE
Route does not exists

### ISSUE THREAD

**Issue by NestPro** [gmaccario/simple-mvc-php-framework#14]
I get **404 not found** when i browse this URL http://localhost//sub-folder/product/1
sub-folder -> is the folder where i installed the project

**Comment by gmaccario** [comment]
Hey @NestPro 

just to be sure: did you set up the `URL_SUBFOLDER` constant to `sub-folder` in `config/config.php`?

**Comment by NestPro** [comment]
> Hey @NestPro
> 
> just to be sure: did you set up the `URL_SUBFOLDER` constant to `sub-folder` in `config/config.php`?

**Comment by NestPro** [comment]
> Hey @NestPro
> 
> just to be sure: did you set up the `URL_SUBFOLDER` constant to `sub-folder` in `config/config.php`?

Yes yes, and when I browse http/localhost/sub-folder it works fine (this redirect me to the homepage)

**Comment by gmaccario** [comment]
Hi @NestPro 

mmm really strange... I tried it by myself, and it works. How is your environment? XAMPP? Or docker? Or what else? Maybe try to check your environment, from the webserver to the htaccess.

![a07e10cd20465fbbb5fa56bf58d479ef](https://user-images.githubusercontent.com/5927739/140768558-a7402b3b-2bfb-451a-89d4-2c8a7c4e2b9c.png)

**Comment by NestPro** [comment]
> Hi @NestPro
> 
> mmm really strange... I tried it, and it works. How is your environment? XAMPP? Or docker? Or what else? Maybe try to check your environment, from the webserver to the htaccess.
> 
> ![a07e10cd20465fbbb5fa56bf58d479ef](https://user-images.githubusercontent.com/5927739/140768558-a7402b3b-2bfb-451a-89d4-2c8a7c4e2b9c.png)

i'm using lamp on linux

**Comment by NestPro** [comment]
![Capture d’écran du 2021-11-08 16-55-31](https://user-images.githubusercontent.com/65047625/140775225-250e73c3-9f74-4b79-b00e-7add72be195e.png)
![Capture d’écran du 2021-11-08 16-58-23](https://user-images.githubusercontent.com/65047625/140775233-811c5b60-c4b8-4319-b922-1042f871e976.png)

**Comment by gmaccario** [comment]
Hi @NestPro 

I want to help you, but it's difficult to understand without any code. 

Have you forked the repo? In this way, I can download it and try it. 

Otherwise, try to do some debug in the Router.php and paste the result here.
