### ISSUE TITLE
Route does not exists.

### ISSUE THREAD

**Issue by khoug** [gmaccario/simple-mvc-php-framework#15]
Nice to greet you,

I would like help with the following problem:

When I insert a file into the public folder, "Route does not exist." In this case the related files go inside the folder:

public/assets/
public/bootstrap/
public/plugins/
public/sass/

I thank you very much in advance if you can help me.

**Comment by gmaccario** [comment]
Hi @khoug 

I need more details: 

- is the basic project working well? or do you get the error immediately?
- are you trying to add a new route? 
- is your project located in a subfolder?

The more details you can add, the better.

Best.
