### ISSUE TITLE
Optional Querystring

### ISSUE THREAD

**Issue by warrickrandi** [gmaccario/simple-mvc-php-framework#17]
How to use an optional query string?

**Comment by warrickrandi** [comment]
Fix the issue & created a pull request

**Comment by gmaccario** [comment]
Hi @warrickrandi 

First of all apologies for the delay in replying to you.

Thanks for your effort, I left a comment in the PR. When you will be able to commit the changes, I will change the code in the article on my site too.

**Comment by warrickrandi** [comment]
I have committed the suggested changes.

**Comment by gmaccario** [comment]
Ty @warrickrandi I managed to include your changes both in the repo and the tutorial.
