### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by DanielLetschka** [gmaccario/simple-mvc-php-framework#2]
Hi,

thanks for your tutorial. Unfortunately i get an ERROR 500 on all existing routes:
- Home
- product/1

Other routes respond with "Route does not exists."

Thanks for your help,
Daniel

**Comment by gmaccario** [comment]
Hi Daniel, thanks for the explanation. I'll try to update the code very soon. I'll let you know

**Comment by gmaccario** [comment]
Hi @DanielLetschka  

I merged a fix, can you check, please?

**Comment by DanielLetschka** [comment]
Wow, very quick! Yes it works now. Many thanks!

**Comment by gmaccario** [comment]
Thanks @DanielLetschka I'll close the issue then
