### ISSUE TITLE
Unknown named parameter $routes in Router.php

### ISSUE THREAD

**Issue by riccardi1997** [gmaccario/simple-mvc-php-framework#20]
```
PHP Fatal error:  Uncaught Error: Unknown named parameter $routes in [Root]\app\Router.php:43
Stack trace:
#0 [Root]\app\Router.php(43): call_user_func_array()
#1 [Root]\app\Router.php(57): App\Router->__invoke()
#2 [Root]\public\index.php(14): require_once('...')
#3 {main}
  thrown in [Root]\app\Router.php on line 43
```

The error above is clear. If you need more details ask me, please. 
Maybe is the problem with __invoke method?

**UPDATES**: After testing session, I see the problem is in array_slice because if I move the 3rd argument from -1 to another number I receive other issues. Below the interested line:
`$params = array_merge(array_slice($matcher, 2, -1), array('routes' => $routes));`

The first issue is in $routes parameter, but my question is what are you expecting from $params variable? It seems you are assigning the wrong value to $params. @gmaccario

**Comment by gmaccario** [comment]
Hello @riccardi1997 

Just a couple of questions:

1. Which PHP version are you using?
2. What is the URL that produces this error? 

Thank you
G.

**Comment by riccardi1997** [comment]
Hello @gmaccario,
sorry it was my fault but I just solved. The problem was I didn't pass RouteCollection obj as param to my indexMethod
You can close the issue, thanks

**Comment by gmaccario** [comment]
@riccardi1997  Thanks for letting me know.
