### ISSUE TITLE
Problem: Route does not exists

### ISSUE THREAD

**Issue by seyedrezabazyar** [gmaccario/simple-mvc-php-framework#22]
I ran the project and got this error: 
`Route does not exists.`

PHP 8.2.1
Apache/2.4.55 (Unix)

**Comment by gmaccario** [comment]
You have to fork the project instead of copying and pasting the project into your Github, like it was yours. 

You completely changed the structure of the project, and from what I can see, you twisted the classes, and you removed the composer files.

So it's up to you now, bc you converted my example into a personal project.

Good luck.

**Comment by seyedrezabazyar** [comment]
What I have published is another project. I want to implement your project for learning

I ran your project on my personal system but it won't run

**Comment by gmaccario** [comment]
Is the project running on a subfolder?
If yes, did you set up the URL_SUBFOLDER constant to the correct sub-folder in config/config.php?

**Comment by seyedrezabazyar** [comment]
This is the way to implement the project:
`http://localhost/test-mvc/simple-mvc-php-framework/`

URL_SUBFOLDER is empth string:
`define('URL_SUBFOLDER', '');`

**Comment by gmaccario** [comment]
Ok try to do this

`define('URL_SUBFOLDER', 'test-mvc');` 

as stated in: https://www.giuseppemaccario.com/how-to-build-a-simple-php-mvc-framework/

This part:
```
Note: if you installed your project into a subfolder as many users seem to do, you must set up URL_SUBFOLDER constant in the config file.
```

**Comment by seyedrezabazyar** [comment]
I tried this before but the problem was not solved

**Comment by gmaccario** [comment]
Ops you're right! This afternoon I overlooked your URL, I forgot the second part of it! Nice catch though.
This issue is definitely closed! :)
