### ISSUE TITLE
Update to PHP8

### ISSUE THREAD

**Issue by AdyGCode** [gmaccario/simple-mvc-php-framework#24]
Could you look at updating to PHP 8.2 or later, especially as PHP 7 is now EOL.

**Comment by gmaccario** [comment]
Hello @AdyGCode thanks for your suggestion! I will, but to do that I need to make some changes to the tutorial too, on my website, I planned to do it but it takes time. I hope you understand. 

Feel free to share your solutions with a Pull Request.
