### ISSUE TITLE
Route not found

### ISSUE THREAD

**Issue by AdyGCode** [gmaccario/simple-mvc-php-framework#25]
Using your repository, have found that the http://HOSTNAME/product/1 URL results in a "URL not found".

Actions taken:
- download repo zip file
- extract to local server
- install composer requirements
- restart apache
- visit site, navigate to the product page

**Comment by gmaccario** [comment]
Hello @AdyGCode

what is the exact route? and is the exact error 'Route does not exists.'?
Is your main folder a subdirectory?
And is the server configured correctly?
