### ISSUE TITLE
Autoloader not working

### ISSUE THREAD

**Issue by TommasoScardi** [gmaccario/simple-mvc-php-framework#26]
When i try to request the homepage an error occurs in Router.php
Cant find \App\Controllers\PageController
`$className = '\\App\\Controllers\\' . $matcher['controller'];
            $classInstance = new $className();`
When the router try to instantiate the Controller class required.

**Comment by TommasoScardi** [comment]
Fixed

**Comment by gmaccario** [comment]
Hello @TommasoScardi thank you for letting me know you found a solution to your question, and for closing the task. 

Feel free to share your solution, it can be useful in the future for the next person! Bye

**Comment by TommasoScardi** [comment]
It was about a mistake that i made overriding defaukt nanesoaces in conposer.json
