### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by pascalwiersma** [gmaccario/simple-mvc-php-framework#27]
Deprecated: Return type of Symfony\Component\Routing\RouteCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in F:\xampp\htdocs\pascalservices-website\vendor\symfony\routing\RouteCollection.php on line 54

Deprecated: Return type of Symfony\Component\Routing\RouteCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in F:\xampp\htdocs\pascalservices-website\vendor\symfony\routing\RouteCollection.php on line 64
Route does not exists.

**Comment by koseus** [comment]
> 

This solved the issue.

**Comment by gmaccario** [comment]
@koseus Thanks for letting me know.
