### ISSUE TITLE
POST request drop MethodNotAllowedException

### ISSUE THREAD

**Issue by pzoli** [gmaccario/simple-mvc-php-framework#6]
if I make a Route with parameters POST request, Routers drop MethodNotAllowedException.
```
$routePostCar` = new Route(constant('URL_SUBFOLDER') . '/car/create', array('controller' => 'CarController', 'method'=>'createNewCar'), array(), array(), '', array(), 'POST');
$routes->add('car_create',$routePostCar);

```

In Router.php(43) I checked the allowed method:

`echo 'Route method is not allowed. Allowed methods:' . json_encode($e->getAllowedMethods());`

it returns ["POST"] :

If I check the method in the controller, I get 'POST'

```
use Symfony\Component\HttpFoundation\Request;

public function createNewCar(RouteCollection $routes) {
        $request = Request::createFromGlobals();
        $data = $request->getMethod();
        var_dump($data);
    }	

```

**Comment by pzoli** [comment]
I use SoapUI for testing. If I chage POST param to GET in Route, the controller call works fine with /car/create, and POST content.

public function createNewCar(RouteCollection $routes) {
       $request = Request::createFromGlobals();
       $data = json_decode($request->getContent());
       Car::create($data);
}

**Comment by gmaccario** [comment]
@pzoli Is my solution working for you?

**Comment by pzoli** [comment]
Ok, tested, works fine.
just delete line 18 in Router.php
```
        $context = new RequestContext();
        $request = Request::createFromGlobals(); //not used $request
        $context->fromRequest(Request::createFromGlobals());

```

**Comment by gmaccario** [comment]
Thanks you.
