### ISSUE TITLE
Static routes

### ISSUE THREAD

**Issue by pzoli** [gmaccario/simple-mvc-php-framework#8]
How can I serve static files like .js and .css?

**Comment by gmaccario** [comment]
@pzoli 

you must use some basic HTML rules:

1. create your files into the public folder (i.e. style.css and main.js);
2. in your views files, link your assets, i.e.:
    <link rel="stylesheet" href="style.css" />
    <script type="application/javascript" src="main.js"></script>

That's it.

If you want to share your assets through multiple views, just use the include function.
